# -*- coding: utf-8 -*-
"""Metode_Polinom_Lagrange.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EyNf_7DuzShoJPuDzCeNGS6pC9tvGe92

**Gina Nabila (21120122130055)**

Metode Numerik - Kelas D

Interpolasi Lagrange
"""

import numpy as np
import matplotlib.pyplot as plt

# Fungsi untuk melakukan interpolasi lagrange
def lagrange_interpolation(x_points, y_points, x):
    n = len(x_points)
    result = 0.0
    for i in range(n):
        term = y_points[i]
        for j in range(n):
            if i != j:
                term *= (x - x_points[j]) / (x_points[i] - x_points[j])
        result += term
    return result

# Fungsi untuk memasukkan jumlah titik dan nilai
def get_user_input():
    n = int(input("Masukkan jumlah titik data: "))
    x_points = []
    y_points = []
    for i in range(n):
        x = float(input(f"Masukkan nilai x({i}): "))
        y = float(input(f"Masukkan nilai y({i}): "))
        x_points.append(x)
        y_points.append(y)
    return x_points, y_points

# Fungsi utama
def main():
    # Mendapatkan nilai yang dimasukkan
    x_points, y_points = get_user_input()

    # Menampilkan titik data yang dimasukkan
    print("Titik data yang dimasukkan:")
    for x, y in zip(x_points, y_points):
        print(f"({x}, {y})")

    # Menghitung nilai interpolasi pada titik tertentu
    x_interpolate = float(input("Masukkan nilai x yang ingin diinterpolasi: "))
    y_interpolate = lagrange_interpolation(x_points, y_points, x_interpolate)
    print(f"Nilai interpolasi pada x = {x_interpolate} adalah y = {y_interpolate}")

    # Membuat grafik interpolasi
    x_plot = np.linspace(min(x_points) - 1, max(x_points) + 1, 1000)
    y_plot = [lagrange_interpolation(x_points, y_points, x) for x in x_plot]

    plt.plot(x_plot, y_plot, color='royalblue', label='Interpolasi Lagrange')
    plt.scatter(x_points, y_points, color='magenta', label='Titik Data')
    plt.scatter([x_interpolate], [y_interpolate], color='mediumpurple', zorder=5, label=f'Interpolasi (x={x_interpolate})')
    plt.xlabel('x')
    plt.ylabel('y')
    plt.title('Interpolasi Lagrange')
    plt.legend()
    plt.grid(True)
    plt.show()

# Menjalankan program utama
if __name__ == "__main__":
    main()